### ISSUE TITLE
can't seem to get the plugin working on Synology Docker

### ISSUE THREAD

**Issue by siwans** [ebaauw/homebridge-p1#13]
this is what the log says after installing Homebridge-p1 and using with /dev/ttyUSB0 with I can see from docker

(node:202) UnhandledPromiseRejectionWarning: Error: spawn udevadm ENOENT                                                                                                           
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)                                                                                                      
    at onErrorNT (internal/child_process.js:407:16)                                                                                                                                
    at process._tickCallback (internal/process/next_tick.js:63:19)                                                                                                                 
(node:202) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecti
ng a promise which was not handled with .catch(). (rejection id: 1)                                                                                                                
(node:202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process wit
h a non-zero exit code.

**Comment by siwans** [comment]
node -v && npm -v && python --version                                                                                                                          
v10.11.0                                                                                                                                                                           
6.4.1                                                                                                                                                                              
Python 2.7.13

**Comment by ebaauw** [comment]
ENOENT typically indicates that a file cannot be found or opened.  What does `serialport-list -f json` give, when called from inside the container?

**Comment by siwans** [comment]
wow that is a fast response....

root@DiskStation:/# serialport-list -f json                                                                                                                                        
{"errno":"ENOENT","code":"ENOENT","syscall":"spawn udevadm","path":"udevadm","spawnargs":["info","-e"]}

**Comment by ebaauw** [comment]
Looks like the [`serialport` module](
https://github.com/node-serialport/node-serialport) doesn’t work in the container.  Homebridge-p1 depends on this module for the connection to the P1 interface.  Looks like it tries to execute `udevadm info -e` but that command seems to be missing from the container.

**Comment by QHose** [comment]
Hi, So any updates on this issue? How can we get this working from inside a container? thanks a lot!

**Comment by jesseplymale** [comment]
For anybody looking at this issue in the future, here is some helpful info for using the `serialport` library within a container.

This link was super helpful: <https://www.losant.com/blog/how-to-access-serial-devices-in-docker>

Make sure that `udevadm` is installed in the image. If you don't have it, do `apt-get update` and `apt-get --assume-yes install udev` to install it in your Dockerfile.

Don't know if this is necessary, but try to create a user in the Dockerfile that has secondary memberships in the linux groups that have permissions to use the devices (using `999` as an example system gid):

- `RUN addgroup --system --gid 999 mysystemuser`
- `RUN adduser --system --uid 999 ---gid 999 mysystemuser`
- `RUN usermod --append --groups plugdev,dialout mysystemuser`
- put a `USER 999` directive at bottom of the Dockerfile Do *not* put `USER 999:999` because specifying the gid along with the uid will cause the secondary groups not to be associated at runtime.

If the USB device is not connected permanently, do the following with `docker run` on your image:

- Set `--privileged` (seems like if you don't specify a `--device` directly and just mount `/dev`, you have to be privileged)
- Bind mount `/dev` into the container so the device can be used
- Bind mount `/run/udev` into the container (can be read-only) so that the `serialport` library can use `udevadm` to look up the serial port.
