### ISSUE TITLE
view option

### ISSUE THREAD

**Issue by ronaldsiesta** [ebaauw/homebridge-p1#46]
Hi Ebaauw,

Thanks for all you efforts to make this Plugin, i'm really happy with it and it works perfectly overhere. I using it mainly in the ave app. placed in room together with my solaragde plugin to see all my energy going in and out.

I have only one question, is it possible to show here the current consumption information instead of the total consumption information? 

Best regards, 

Ronald

**Comment by ebaauw** [comment]
Not sure what you mean by “here”?  The current consumption is exposed as `Consumption` (in W).  It’s up to Eve how to display it.

**Comment by ronaldsiesta** [comment]
with "here" i mean the room slide. 
<img width="1017" alt="Schermafbeelding 2021-02-26 om 16 19 15" src="https://user-images.githubusercontent.com/77148687/109318866-90f9bc00-784e-11eb-9d52-78074f017964.png">

**Comment by ebaauw** [comment]
I can expose the meters as `Outlet`.  Of course, you cannot turn the meter on or off, so the outlet would show as on all the time (and revert to on when you try and turn it off).  That has the added advantage of not needing a dummy `Stateless Programmable Switch` to un-favourite the _Not Supported_ accessory in Home.

In the _Room_ view, Eve shows the light with an On/Off switch on the right, but with the `Consumption` under the name.

I'm not going to create fake light sensors.

**Comment by stannie** [comment]
It's most probably more an Eve question, but with this change I only see the button state (ON) in At a Glance and in the room screens, not the consumption / delivery W. Checked both iPhone and iPad.

**Comment by ebaauw** [comment]
Indeed _At a Glance_ only shows the button.  You should see the current consumption in the _Rooms_ view, as in the screenshot above.  Maybe you need to restart Eve, or change the order of the characteristics (I have _On_, _Total Consumption_, _Current Consumption_ as first three).

I could try and expose two additional custom services, one with _Total Consumption_ and one with _Current Consumption_ for inclusion in the _At a Glance_ view.  Home should ignore these, but I'm not sure if Eve will still honour the history...

**Comment by ebaauw** [comment]
Eve is definitely peculiar.  I reverted the change to expose the meters as `Outlet` and changed the order in which the characteristics for the _Electricity_ service are created.  It now shows the `Current Consumption` (and _Last Updated_) in the _Rooms_ view, instead of the _Total Consumption Normal_ and _Total Consumption Low_.  You might need to un-expose and re-expose the accessory, before Eve picks up the change (i.e. delete the accessory from `cachedAccessories` and restart Homebridge).

![IMG_0002](https://user-images.githubusercontent.com/22179355/109655523-a549fb80-7b63-11eb-8de9-98b554346258.PNG)

**Comment by ebaauw** [comment]
In v1.1.9.

**Comment by ronaldsiesta** [comment]
This gifs a good quick view, thank you :)
