### ISSUE TITLE
Does your plugin support a wifi gateway instead of a USB cable?

### ISSUE THREAD

**Issue by tooh** [ebaauw/homebridge-p1#51]

**Comment by ebaauw** [comment]
Short answer: no.

Long answer: If the Wifi gateway provides a protocol similar to the P1, I might have a look.  Homebridge P1 itself can relay the P1 telegrams over a web socket connection, and another instance of Homebridge P1 can use that instead of the serial interface provided by the USB cable (I use that for testing).  Note that in both cases, the P1 cable and the web socket, Homebridge P1 receives a push notification per telegram.  Any wifi gateway would need to provide a very similar interface; Homebridge P1 will not call an API to receive data and will not query a database.

**Comment by tooh** [comment]
OK. Thanks for your answer.

I am considering to buy this device

https://www.homewizard.nl/shop/energy/homewizard-wi-fi-p1-meter
