### ISSUE TITLE
Price per kwh setting in eve app??

### ISSUE THREAD

**Issue by Maykel1969** [ebaauw/homebridge-p1#53]
Hi Erik,
I run your plugin on a meter which sends data every 5 sec and it seems to be stable. Also the graphs work fine.
But for some reason I can not find the cost per kwh setting in the EVE app.
Any idea why this setting is not visible??
Grt
Maykel

**Comment by ebaauw** [comment]
It should be under _Settings_ | _General_ | _Energy Cost_.

**Comment by Maykel1969** [comment]
I see the general tab but it only shows:
- home name
- Icon and color
- Location/open settings
- Home hub

is this the right menu??

**Comment by ebaauw** [comment]
Yes, it should appear right under Home hub.  Maybe Eve only shows it when it thinks it has an Eve Energy connected?  Are _Total Cost_ and _Projected Cost_ for electricity showing any numbers?

I probably need to expose electricity as an _Outlet_ to fool Eve into thinking it is an Eve Energy.  That comes with mandatory _On_ and _In Use_ characteristics and Home would show it as a Power Point, Fan, or Light (depending on the setting).  I did try before to make the _On_ characteristic read-only, but Home and, I think, Eve choked on that.  I could automatically turn the "outlet" back off.  I settled on a custom service, because it didn't make sense to me, semantically.  Then, of course, I needed to add the dummy stateless switch to un-favourite the meter in iOS 14 and beyond, which doesn't make sense semantically either.

**Comment by Maykel1969** [comment]
Total cost and projected cost are goog values. So there is a value set for €/kwh. Only thing is that I cannot change it.
I’m new to thus plugin so i’m just playing with it.
Normally i do not use eve so hopefully apple will add this feature in the coming ios update….

keep up the good work!!

**Comment by ebaauw** [comment]
I removed the Eve Engery from my test network, and, indeed, the _Energy Cost_ disappeared from Eve.  After exposing the _Electricity_ and _Gas_ accessories using _Outlet_ services, Eve once again shows it.  However, in the _Room_ view, Eve no longer shows the _Total Consumption_; it shows an _Off_|_On_ slider instead.  The _On_ characteristic, of course, doesn't do anything.

I think I prefer the current setup as custom service with a _Stateless Programmable Switch_.  Best make this optional: I've added a `config.json` key to expose the meters as _Outlet_ in v1.2.8.

**Comment by Maykel1969** [comment]
I’ll give it a try as soon as I ran my cable via its final route.
Over the flour in the hallway has a very low WAF :-)
