### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-p1#6]
I want to install this plugin, but before a purchase the cable, can somebody send some screenshots how this plugin is expose in the Apple HomeKit app and the Eve app?

**Comment by ebaauw** [comment]
Here's the screenshots from Eve:
![img_0075](https://user-images.githubusercontent.com/22179355/39694098-676be21e-51e6-11e8-942d-dff1bc6e9b88.png)
![img_0076](https://user-images.githubusercontent.com/22179355/39694101-69b06b26-51e6-11e8-91f3-733117b11774.png)
The _Electricity_ updates every seconds, the _Gas_ every 15 minutes.  Of course, _Gas_ is in m³ instead of kWh, but Eve has hard-coded the unit.  I need to use the same characteristic, or Eve won't show the history.

Apple's Home app doesn't support any of this.

**Comment by tomsteenbakkers** [comment]
Thanks, I bought the cable. Now trying to get the software working.
